### ISSUE TITLE
Extension is interfering with 'Track Item in Solution Explorer' setting

### ISSUE THREAD

**Issue by DanAtkinson** [tunnelvisionlabs/FindInSolutionExplorer#15]
Hi there,

This extension seems to be interfering with the ability to keep the 'Track Item in Solution Explorer' setting unchecked in VS2017 (including the latest version).

For some reason, the option keeps getting rechecked and, if the extension is removed, the problem no longer occurs.

This has also been detailed and discussed on the MS Developer Community [here](https://developercommunity.visualstudio.com/content/problem/55144/choice-for-track-active-item-in-solution-explorer.html).

Thanks, Dan

**Comment by vtabota** [comment]
Same here

**Comment by bodong1987** [comment]
I have the same problem.

**Comment by bodong1987** [comment]
this problem is occur when i open multiple visual studio instances.

**Comment by sharwell** [comment]
This extension duplicates functionality that is built into Visual Studio 2012 and newer. For users that want to use the "Track Item in Solution Explorer" setting, I recommend switching to the built-in feature to avoid interference from an extension.

**Comment by bodong1987** [comment]
i don't need the internal functionality of "Track Item in solution explorer", but if i install this extension, when i opened multiple instance of visual studio, this extension will cause the setting "Track Item in Solution Explorer" checked, but i have never checked this setting manully.
