### ISSUE TITLE
Uninstall from VS2019 fails

### ISSUE THREAD

**Issue by pm64** [tunnelvisionlabs/FindInSolutionExplorer#19]
Once this extension is installed in VS2019, it can never be uninstalled.

It's possible to click the "Uninstall" button, and VS2019 will report that the extension will be removed when VS2019 closes. But the uninstall never takes place.

**Comment by sharwell** [comment]
😕 That's super strange. Does it report an error?

**Comment by pm64** [comment]
Apologies for the delayed response. No, it did not report an error.

**Comment by sharwell** [comment]
Maybe VS never closed? Is there a devenv.exe process hanging around?

**Comment by pm64** [comment]
I apologize but I no longer have that development environment available for testing. If you're unable to reproduce the issue, I'd say you can close this.

**Comment by sharwell** [comment]
Thanks for the update! Sorry to hear it was causing problems.
